env:
  browser: true
  es6: true
  node: true
  meteor: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Roles: readonly
  Accounts: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
settings:
  react:
    version: detects
